# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b01c94bfcfadcf30e6ed3f1e24ee28ec8294ebf3291a0a4eb31b9dad98d484d1e650dbf69a18e5079e6fa36f3d7f7d1804a3d815febdcbd3c5158692bcb7e07

test:
  secret_key_base: 84e0e5290da9616a1ea208ddff991983f76cf8e07bfea6d2226cae5119ab0be859ce1a23785caae4f7e735a2bf7446c688cff06ee50d1c10a0075f07508869fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
